# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61cec1a37b02351219f6605aba1cf42e757ce35c981fb8e0dbfc7318330017e8d04776acd1bea32f7cb0871ab105b31b6fb949a4f5d4493eb4b4d00fcbded20d

test:
  secret_key_base: e147939d2e098f0219dd7002660d78ecdb2d6f6c1fa2c63246f5305f0c02d164f7d3959bf30b33977e57ab3133569a1c22e311178d21796de3fddc806ad6c599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
